version: "3.9"

services:
  smartsheet-app:
    build:
      context: .
    image: smartsheet-extractor-app:latest
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /mnt/smartsheet:/mnt/smartsheet
    command: ["python", "app/app.py"]
    restart: unless-stopped
